language: python

install:
    - pip install mkdocs
    - pip install mkdocs-material
    - pip install pymdown-extensions
    - pip install pygments

script:
    - mkdocs build --verbose --clean --strict

deploy:
  provider: pages
  skip-cleanup: true
  target-branch: master
  github-token: ${ACCESS_TOKEN}
  keep-history: true
  local_dir: site
  on:
    branch: development
